//
// Created by Lady Asura III on 25/9/2019.
//

#ifndef LAB_7_POO_LISTAS_ORIGAMY4321_LISTAVEHICULOS_H
#define LAB_7_POO_LISTAS_ORIGAMY4321_LISTAVEHICULOS_H


class ListaVehiculos {

};


#endif //LAB_7_POO_LISTAS_ORIGAMY4321_LISTAVEHICULOS_H
