//
// Created by Lady Asura III on 20/9/2019.
//

#ifndef LAB_7_POO_LISTAS_ORIGAMY4321_MOTOCICLETA_H
#define LAB_7_POO_LISTAS_ORIGAMY4321_MOTOCICLETA_H


class Motocicleta {

};


#endif //LAB_7_POO_LISTAS_ORIGAMY4321_MOTOCICLETA_H
